---
namespace: rhpds
name: ocp_dev_days_rdshw
version: 1.0.0
readme: README.md
authors:
  - Red Hat GPTE
description: OpenShift Dev Day Roadshow workload collection for cluster and tenant bootstrap
license:
  - Apache-2.0
tags:
  - openshift
  - workload
  - bootstrap
  - devdays
dependencies: {}
repository: https://github.com/rhpds/ocp-dev-days-rdshw
